# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeitem',
            name='access_staff',
            field=models.BooleanField(db_index=True, default=False, help_text='Check it to grant access to this item to staff members only.', verbose_name='Staff members only'),
        ),
        migrations.AddField(
            model_name='treeitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Site tree item icon for menu.', max_length=20, null=True, verbose_name='Icon'),
        ),
    ]
